// <auto-generated />
using System;
using DemoTradeLab.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoTradeLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DemoTradeLabDbContext))]
    [Migration("20260806200612_AddOrderRecoveryWorkflow")]
    partial class AddOrderRecoveryWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DemoTradeLab.Core.DemoProfiles.DemoAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemoProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReservedBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoProfileId", "Key")
                        .IsUnique();

                    b.ToTable("DemoAccounts", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.DemoProfiles.DemoProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("DemoProfiles", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.Orders.DemoOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemoAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoAccountId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("DemoOrders", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.Orders.DemoOrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "OccurredAtUtc");

                    b.ToTable("DemoOrderEvents", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.Reservations.DemoReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemoAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoAccountId");

                    b.HasIndex("DemoAccountId", "CreatedAtUtc");

                    b.ToTable("DemoReservations", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.Reservations.ReservationAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemoAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("DemoAccountId", "OccurredAtUtc");

                    b.ToTable("ReservationAuditEntries", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.Reservations.ReservationCompletionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemoAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("DemoAccountId", "Key")
                        .IsUnique();

                    b.ToTable("ReservationCompletionRecords", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.Reservations.ReservationIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemoAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("DemoAccountId", "Key")
                        .IsUnique();

                    b.ToTable("ReservationIdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.Trades.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClosingPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fees")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FinancingCosts")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealizedProfitLoss")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAtUtc");

                    b.HasIndex("Instrument");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("DemoTradeLab.Core.DemoProfiles.DemoAccount", b =>
                {
                    b.HasOne("DemoTradeLab.Core.DemoProfiles.DemoProfile", null)
                        .WithMany("Accounts")
                        .HasForeignKey("DemoProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DemoTradeLab.Core.Orders.DemoOrder", b =>
                {
                    b.HasOne("DemoTradeLab.Core.DemoProfiles.DemoAccount", null)
                        .WithMany()
                        .HasForeignKey("DemoAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoTradeLab.Core.Reservations.DemoReservation", null)
                        .WithOne()
                        .HasForeignKey("DemoTradeLab.Core.Orders.DemoOrder", "ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DemoTradeLab.Core.Orders.DemoOrderEvent", b =>
                {
                    b.HasOne("DemoTradeLab.Core.Orders.DemoOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DemoTradeLab.Core.Reservations.DemoReservation", b =>
                {
                    b.HasOne("DemoTradeLab.Core.DemoProfiles.DemoAccount", null)
                        .WithMany()
                        .HasForeignKey("DemoAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DemoTradeLab.Core.Reservations.ReservationAuditEntry", b =>
                {
                    b.HasOne("DemoTradeLab.Core.DemoProfiles.DemoAccount", null)
                        .WithMany()
                        .HasForeignKey("DemoAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoTradeLab.Core.Reservations.DemoReservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DemoTradeLab.Core.Reservations.ReservationCompletionRecord", b =>
                {
                    b.HasOne("DemoTradeLab.Core.DemoProfiles.DemoAccount", null)
                        .WithMany()
                        .HasForeignKey("DemoAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoTradeLab.Core.Reservations.DemoReservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DemoTradeLab.Core.Reservations.ReservationIdempotencyRecord", b =>
                {
                    b.HasOne("DemoTradeLab.Core.DemoProfiles.DemoAccount", null)
                        .WithMany()
                        .HasForeignKey("DemoAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoTradeLab.Core.Reservations.DemoReservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DemoTradeLab.Core.DemoProfiles.DemoProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
